quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus_user
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_tasks

# Borra y recrea las tablas automáticamente basándose en las entidades @Entity
quarkus.hibernate-orm.database.generation=drop-and-create